import type { SeoLanding } from "@/lib/seo-content";

type Occasion = SeoLanding & { label: string; line: string; detail: string };
const passion = { src: "/passion/WhatsApp Image 2026-08-16 at 21.29.22.jpeg", alt: "Passion: letto, luci soffuse e jacuzzi nella suite Euphoria" };
const infinity = { src: "/infinity/WhatsApp Image 2026-08-16 at 21.29.16 (1).jpeg", alt: "Infinity: ambienti e illuminazione della suite Euphoria a Porto Empedocle" };

export const OCCASIONS: Occasion[] = ([
  {
    slug: "anniversario-matrimonio-agrigento", label: "Anniversario", line: "Ancora voi.\nCome la prima volta.", detail: "Una data vostra, una porta da chiudere, tutto il tempo per ritrovarsi.",
    primaryKeyword: "anniversario di matrimonio Agrigento", title: "Anniversario di matrimonio vicino ad Agrigento",
    metaTitle: "Anniversario di matrimonio ad Agrigento: una suite per due",
    metaDescription: "Festeggia il vostro anniversario da Euphoria, a Porto Empedocle: jacuzzi e sauna private, aperitivo incluso e allestimento romantico su richiesta.",
    ogTitle: "Il vostro anniversario, dentro Euphoria", ogDescription: "Una notte per ritrovarsi a Porto Empedocle, vicino ad Agrigento.", suggestedSuite: "passion",
    hero: { eyebrow: "Il vostro anniversario", h1: "Ancora voi. Come la prima volta.", sub: "Un anniversario di matrimonio vicino ad Agrigento, con una suite tutta per voi. A Porto Empedocle, Passion e Infinity lasciano spazio alle cose che durante l’anno rimandate: un brindisi, un bagno lungo, una sera insieme.", image: passion },
    blocks: [
      { title: "Una ricorrenza che non finisce dopo cena", body: "Per il primo anniversario, dieci anni insieme o le nozze d’argento, potete dedicare alla coppia un’intera notte. L’aperitivo di benvenuto comprende un tagliere di salumi e una bottiglia di prosecco. Jacuzzi e sauna sono interne alla suite: dopo il brindisi, la serata continua senza spostarvi." },
      { title: "La sorpresa comincia prima di aprire la porta", body: "Il pacchetto romantico essenziale, da €10 oltre al soggiorno, prevede petali, luci accese e suite climatizzata all’arrivo. Una dedica, dei fiori o una torta sono richieste da valutare insieme: comunicateci l’idea e il budget prima di prenotare, per concordare disponibilità e costo.", bullets: ["Indicate la data e quale anniversario festeggiate.", "Scegliete Passion per un ambiente raccolto o Infinity per più spazio.", "Concordate orario di arrivo e dettagli dell’allestimento."] },
      { title: "Solo voi, oppure una giornata in Sicilia", body: "Euphoria si trova a Porto Empedocle, in provincia di Agrigento. Potete abbinare il soggiorno a una passeggiata sul mare o a una visita alla Valle dei Templi, verificando separatamente accessi e orari. Se preferite restare dentro, entrambe le suite hanno una cucina completa con forno." },
    ],
    faqs: [{ q: "Quanto costa una notte per l’anniversario?", a: "Il pernottamento parte da €150 a coppia con aperitivo incluso. Il prezzo effettivo dipende dalle date; gli allestimenti sono extra da concordare." }, { q: "Posso organizzare tutto senza rovinare la sorpresa?", a: "Scriveteci prima dell’arrivo e indicate come preferite essere contattati. Concordiamo insieme i dettagli e i tempi della preparazione." }, { q: "È adatta anche a un anniversario di fidanzamento?", a: "Sì, la stessa esperienza può accompagnare un anniversario di fidanzamento o un’altra data importante per voi." }], relatedBlogSlugs: ["anniversario-sorpresa-romantica-jacuzzi"],
  },
  {
    slug: "proposta-matrimonio-suite-agrigento", label: "La proposta", line: "Una domanda.\nIl vostro mondo.", detail: "L’atmosfera per dirlo, l’intimità per sentirlo. Il resto lo scrivete voi.",
    primaryKeyword: "proposta matrimonio privata Agrigento", title: "Proposta di matrimonio in suite vicino ad Agrigento", metaTitle: "Proposta di matrimonio in suite ad Agrigento | Euphoria", metaDescription: "Organizza una proposta di matrimonio intima a Porto Empedocle. Suite con jacuzzi e sauna private, dettagli e allestimento da concordare con Euphoria.", ogTitle: "Una domanda. Il vostro mondo.", ogDescription: "La vostra proposta di matrimonio in una suite privata Euphoria.", suggestedSuite: "passion",
    hero: { eyebrow: "La domanda più bella", h1: "Una domanda. Il vostro mondo.", sub: "Per una proposta di matrimonio intima vicino ad Agrigento, scegliete uno spazio in cui sentirvi a casa, con una luce diversa. Euphoria, a Porto Empedocle, è il punto di partenza per costruire il vostro momento.", image: passion },
    blocks: [
      { title: "Il momento giusto può essere a porta chiusa", body: "Se immaginate una proposta lontana dal pubblico di un ristorante, una suite permette di scegliere il vostro ritmo. Potete chiederglielo all’arrivo, dopo l’aperitivo di benvenuto oppure durante una serata preparata con calma. Non serve trasformare il momento in uno spettacolo." },
      { title: "Prepariamo i dettagli insieme", body: "Raccontateci l’idea prima di confermare: data, suite, budget, fiori o dedica. Il pacchetto essenziale da €10 comprende petali e atmosfera pronta all’arrivo. Ogni altro elemento va verificato e quotato; fotografo, composizioni floreali e servizi esterni non sono inclusi nel pernottamento.", bullets: ["Condividete una breve descrizione della sorpresa.", "Concordate preparazione e orario di ingresso.", "Se desiderate un fotografo, verificate prima accesso e presenza di persone esterne."] },
      { title: "Passion per stare vicini, Infinity per più respiro", body: "Passion riunisce letto, jacuzzi e sauna in un ambiente da 55 m². Infinity offre 77 m² con living e cucina, per chi desidera spazi più articolati. Le foto delle due suite aiutano a immaginare dove vivere la proposta; la disponibilità dipende dalla data richiesta." },
    ], faqs: [{ q: "Potete allestire la suite prima dell’arrivo?", a: "La preparazione romantica è disponibile su richiesta. Comunicateci i dettagli in anticipo: confermeremo cosa è realizzabile e il relativo prezzo." }, { q: "La proposta include un fotografo?", a: "No. Se volete coinvolgere un professionista, la sua presenza e gli orari vanno concordati prima con la struttura." }, { q: "Si può prenotare solo per la proposta, senza pernottare?", a: "L’offerta pubblicata riguarda il pernottamento. Per utilizzi diversi chiedete disponibilità e condizioni: non è prevista qui una tariffa a ore." }],
  },
  {
    slug: "compleanno-romantico-agrigento", label: "Compleanno in due", line: "Il regalo?\nEsserci davvero.", detail: "Una sorpresa a porta chiusa. Un brindisi, la jacuzzi e nessuna fretta.",
    primaryKeyword: "compleanno romantico Agrigento", title: "Compleanno romantico vicino ad Agrigento", metaTitle: "Compleanno romantico ad Agrigento: sorpresa in suite", metaDescription: "Un’idea per il compleanno del partner: una notte Euphoria a Porto Empedocle con jacuzzi, sauna e aperitivo. Torta e sorprese da concordare.", ogTitle: "Un compleanno da vivere in due", ogDescription: "Regalatevi una notte Euphoria a Porto Empedocle.", suggestedSuite: "infinity",
    hero: { eyebrow: "Il compleanno, a modo vostro", h1: "Il regalo? Esserci davvero.", sub: "Cercate un’idea per il compleanno del vostro partner in zona Agrigento? A Porto Empedocle potete trasformare il regalo in una notte insieme, tra jacuzzi privata, sauna e un brindisi di benvenuto.", image: infinity },
    blocks: [
      { title: "Un compleanno pensato per due", body: "Una cena, un film, un bagno in jacuzzi: componete la serata con quello che vi piace. Infinity offre una zona living e una cucina completa; Passion raccoglie l’esperienza in un ambiente più intimo. Il soggiorno è pensato per la coppia. Per ospiti aggiuntivi o altre esigenze occorre una conferma specifica." },
      { title: "Dalla dedica alla torta: cosa concordare", body: "Una sorpresa funziona quando i dettagli sono pronti. Chiedete in anticipo se è possibile predisporre una torta, fiori o una dedica e indicate preferenze ed eventuali esigenze alimentari. Disponibilità, consegna e costi si definiscono insieme; questi elementi non sono compresi automaticamente nell’aperitivo incluso.", bullets: ["Data del compleanno e orario previsto di arrivo.", "Suite preferita e budget per gli extra.", "Dettagli della sorpresa da confermare prima del soggiorno."] },
      { title: "Regalate una data da aspettare", body: "Se conoscete già gli impegni del partner, chiedete disponibilità per una notte precisa. Se volete lasciare libera la scelta, contattateci per capire come organizzare il regalo: eventuali formule, validità e modalità di pagamento devono essere confermate direttamente." },
    ], faqs: [{ q: "La torta è inclusa?", a: "No. Il soggiorno include l’aperitivo di benvenuto; torta e allestimenti personalizzati vanno richiesti e quotati separatamente." }, { q: "Posso organizzare una festa con amici?", a: "Questa proposta è per un compleanno in coppia. Prima di prevedere invitati o una festa, chiedete alla struttura se l’utilizzo è possibile e a quali condizioni." }, { q: "Posso regalare una notte senza scegliere subito la data?", a: "Contattateci per verificare se è possibile e concordare le condizioni. Non viene promesso un voucher a data aperta senza conferma." }],
  },
  {
    slug: "location-shooting-fotografico-agrigento", label: "Shooting & creatività", line: "La vostra visione.\nUna luce diversa.", detail: "Ritratti, progetti di coppia, contenuti di brand. Immaginate il vostro set.",
    primaryKeyword: "location shooting fotografico Agrigento", title: "Location per shooting fotografico vicino ad Agrigento", metaTitle: "Location shooting fotografico Agrigento: suite Euphoria", metaDescription: "Cerchi una suite per shooting a Porto Empedocle, vicino ad Agrigento? Scopri gli ambienti Euphoria e proponi il progetto: accessi, orari e uso da concordare.", ogTitle: "Euphoria, una luce diversa per il vostro progetto", ogDescription: "Proponete il vostro shooting nelle suite di Porto Empedocle. Utilizzo su richiesta.", suggestedSuite: "infinity",
    hero: { eyebrow: "Spazio alla vostra visione · su richiesta", h1: "La vostra visione. Una luce diversa.", sub: "Per uno shooting fotografico in zona Agrigento, gli ambienti di Euphoria a Porto Empedocle offrono un’estetica riconoscibile: luci colorate, jacuzzi e interni da esplorare. L’utilizzo come location va concordato prima della prenotazione.", image: infinity },
    blocks: [
      { title: "Ritratti, coppie e contenuti di brand", body: "Un ritratto editoriale, un servizio di coppia o contenuti per un progetto creativo possono partire dall’atmosfera delle suite. Le fotografie pubblicate mostrano gli ambienti reali: usatele per costruire una moodboard e spiegare quali inquadrature desiderate. La struttura valuta il progetto e la compatibilità con gli spazi prima di confermare." },
      { title: "Quale suite per il vostro set?", body: "Infinity, con 77 m² tra zona notte, living e cucina, permette di immaginare più ambientazioni. Passion, da 55 m², ha una composizione più raccolta, con letto e jacuzzi vicini. Le metrature non definiscono la capienza di una troupe: dimensioni delle attrezzature, passaggi e numero di persone vanno verificati insieme." },
      { title: "Un brief semplice, prima di prenotare", body: "Inviate data, durata, numero di persone, finalità delle immagini e attrezzatura prevista. Segnalate se intendete coinvolgere modelli, make-up artist o altri professionisti, usare la jacuzzi nelle riprese o spostare elementi. Tempi di preparazione e riordino devono rientrare negli accordi.", bullets: ["Tipologia di progetto e riferimenti visivi.", "Orari di ingresso e uscita, compreso montaggio e riordino.", "Troupe, luci, supporti e necessità di alimentazione.", "Uso personale, editoriale o commerciale dei contenuti."] },
      { title: "Una location da valutare, con condizioni dedicate", body: "Il prezzo del pernottamento non è un preventivo per produzioni fotografiche o video. Non sono inclusi fotografo, attrezzature, styling o assistenza di produzione. Disponibilità, uso commerciale degli ambienti, accessi e prezzo vengono concordati in base al progetto. Chiedete una conferma prima di fissare gli appuntamenti con la troupe." },
    ], faqs: [{ q: "Posso prenotare online una suite e portare la troupe?", a: "Prima di prenotare per uno shooting occorre concordare il progetto, il numero di persone e l’utilizzo degli ambienti. Una prenotazione per pernottamento non conferma automaticamente l’uso come set." }, { q: "È possibile realizzare video e contenuti social?", a: "Potete proporre anche riprese video e contenuti social. Finalità, attrezzature, durata e condizioni di utilizzo devono essere approvate prima." }, { q: "Fornite luci professionali o fotografo?", a: "Non sono servizi inclusi nell’offerta pubblicata. Organizzate il team e segnalate le attrezzature necessarie per verificare la compatibilità con la suite." }, { q: "Dove si trova la location?", a: "Euphoria si trova in Via Marullo 2 a Porto Empedocle, in provincia di Agrigento. Accessi e modalità di carico delle attrezzature vanno verificati direttamente." }],
  },
  {
    slug: "suite-notte-nozze-agrigento", label: "Notte di nozze", line: "Dopo tutti.\nFinalmente voi.", detail: "Il primo capitolo dopo il sì. Silenzio, acqua calda e intimità.",
    primaryKeyword: "suite notte di nozze Agrigento", title: "Suite per la notte di nozze vicino ad Agrigento", metaTitle: "Suite notte di nozze Agrigento: jacuzzi e sauna private", metaDescription: "La vostra notte di nozze a Porto Empedocle: suite Euphoria con jacuzzi, sauna e ingresso con codice. Concordate arrivo dopo il ricevimento e allestimento.", ogTitle: "Dopo tutti. Finalmente voi.", ogDescription: "La notte di nozze nelle suite Euphoria a Porto Empedocle.", suggestedSuite: "infinity",
    hero: { eyebrow: "Il primo capitolo dopo il sì", h1: "Dopo tutti. Finalmente voi.", sub: "Dopo gli abbracci, le fotografie e l’ultimo ballo, una suite tutta vostra. Euphoria accoglie la vostra notte di nozze a Porto Empedocle, in zona Agrigento, con jacuzzi e sauna interne.", image: infinity },
    blocks: [
      { title: "Il rientro fa parte della festa", body: "L’ingresso con tastierino permette di accedere con un codice. Se prevedete di rientrare dopo il ricevimento, comunicate prima l’orario e completate le indicazioni richieste dalla struttura. L’accesso autonomo non sostituisce gli accordi su check-in e check-out: definite tutto prima, per godervi la giornata." },
      { title: "Più spazio per abiti e piccoli rituali", body: "Infinity offre 77 m² con zona notte, living e cucina: una scelta da considerare per distendersi dopo una giornata intensa. Passion è più raccolta, da 55 m². Entrambe hanno jacuzzi e sauna private, così il soggiorno può continuare senza un percorso benessere condiviso." },
      { title: "Una notte, oppure ancora un giorno insieme", body: "Potete chiedere disponibilità per prolungare il soggiorno e iniziare con calma il giorno successivo. Se desiderate un allestimento romantico, comunicatelo in anticipo. Preparativi degli sposi, accesso di fotografi o parrucchieri e uscite posticipate sono esigenze distinte, da verificare prima di confermare.", bullets: ["Data del matrimonio e arrivo previsto dopo il ricevimento.", "Suite preferita e numero di notti.", "Eventuale allestimento e richieste per la mattina successiva."] },
    ], faqs: [{ q: "Possiamo arrivare dopo il ricevimento?", a: "Comunicate l’orario previsto prima di prenotare. L’ingresso avviene con codice, ma tempi e procedure di arrivo devono essere concordati con la struttura." }, { q: "Il late check-out è incluso?", a: "No, non è incluso automaticamente. Chiedete se è disponibile per la vostra data e a quali condizioni." }, { q: "Si possono fare i preparativi degli sposi in suite?", a: "È una richiesta da valutare separatamente: indicate orari, professionisti presenti e necessità prima di prenotare." }],
  },
  {
    slug: "spa-privata-mamma-figlia-porto-empedocle", label: "Mamma & Figlia", line: "Voi due.\nNessun altro.", detail: "Un pomeriggio o una serata tra voi. Jacuzzi, sauna e una porta da chiudere.",
    primaryKeyword: "spa privata mamma figlia Porto Empedocle", title: "Spa privata mamma e figlia vicino ad Agrigento", metaTitle: "Spa privata mamma e figlia Porto Empedocle | Euphoria",
    metaDescription: "Un pomeriggio o una serata tra mamma e figlia a Porto Empedocle: spa privata in suite, jacuzzi e sauna interne, nessun pubblico. Aperitivo incluso per il pernottamento.",
    ogTitle: "Voi due. Nessun altro.", ogDescription: "Spa privata in suite tra mamma e figlia, a Porto Empedocle in provincia di Agrigento.", suggestedSuite: "passion", relatedBlogSlugs: ["spa-privata-mamma-figlia-perche-funziona"],
    hero: { eyebrow: "Solo voi due", h1: "Voi due. Nessun altro.", sub: "Se cercate un momento privato tra mamma e figlia in provincia di Agrigento, Euphoria è uno spazio chiuso dove entrambe potete rilassarvi senza incrociare altre persone. A Porto Empedocle, Passion e Infinity offrono jacuzzi e sauna interne con ingresso autonomo e aperitivo incluso per il pernottamento.", image: passion },
    blocks: [
      { title: "Non è una spa “per categoria”: è un posto vostro per qualche ora", body: "Non serve un pacchetto con nome per stare insieme. Basta una porta da chiudere, una jacuzzi dove rimanere a lungo e una sauna senza turno. Le due suite sono chiuse e autonome: dentro la stanza non vedrete nessun’altra persona per tutta la durata." },
      { title: "Cucina completa, ingresso autonomo e zero fretta", body: "Potete portare caffè, bibite o quello che preferite: entrambe le suite hanno una cucina completa con forno. L’ingresso con tastierino vi permette di arrivare all’orario concordato, senza passare da una reception comune. Il pernottamento include l’aperitivo di benvenuto con tagliere e una bottiglia di prosecco.", bullets: ["Indicate data e formula preferita (day use o pernottamento).", "Scegliete Passion per un ambiente più raccolto o Infinity per più spazio.", "Concordate l’orario di ingresso prima dell’arrivo."] },
      { title: "Passion 55 m² per stare vicine, Infinity 77 m² per muovervi comode", body: "Passion raccoglie letto, jacuzzi e sauna in uno spazio unico da 55 m², ideale per due persone che vogliono restare vicino. Infinity offre 77 m² con zona living e cucina più ampia: utile se preferite più spazio per sistemarvi, bere qualcosa o scattare fotografie senza stare strette." },
    ], faqs: [{ q: "È possibile solo per un pomeriggio, senza pernottare?", a: "Scriveteci su WhatsApp: la disponibilità per un utilizzo diurno si verifica di volta in volta e non è automatica." }, { q: "Possiamo usare la cucina per caffè o bibite?", a: "Sì, la cucina è completa e disponibile. Non sono inclusi però generi alimentari o bevande extra oltre all’aperitivo del pernottamento." }, { q: "Possiamo venire in 3 persone (per esempio sorella aggiuntiva)?", a: "Ogni composizione diversa da due va concordata prima della prenotazione, per verificare condizioni e tariffa." }],
  },
  {
    slug: "pre-wedding-spa-privata-sposa-testimone", label: "Pre-Wedding", line: "Prima di tutti.\nSolo voi.", detail: "Sauna, jacuzzi e prosecco. Il giorno prima, o quando preferite.",
    primaryKeyword: "pre wedding spa privata sposa testimone Agrigento", title: "Spa privata pre-wedding vicino ad Agrigento", metaTitle: "Pre wedding spa privata: sposa e testimone | Euphoria", metaDescription: "Uno spazio privato a Porto Empedocle per sposa, testimone o migliori amiche prima del matrimonio. Jacuzzi e sauna in suite, ingresso autonomo. Dettagli e orari da concordare prima.", ogTitle: "Prima di tutti. Solo voi.", ogDescription: "Pre-wedding in una suite Euphoria: privacy totale per sposa e testimone.", suggestedSuite: "infinity", relatedBlogSlugs: ["pre-wedding-idea-spa-privata-sposa-amica", "regalo-spa-privata-agrigento"],
    hero: { eyebrow: "Sposa e testimone, in privato", h1: "Prima di tutti. Solo voi.", sub: "Se avete bisogno di un momento riservato prima del matrimonio, Euphoria è una suite privata a Porto Empedocle, in provincia di Agrigento. Potete venire il giorno prima, la sera prima o qualche giorno prima dell’evento. L’ingresso è autonomo e non incrociate altro pubblico.", image: infinity },
    blocks: [
      { title: "La spa “di gruppo” in hotel non serve a nessuno il giorno prima", body: "Il giorno più vicino al matrimonio, la sposa e le sue persone fidate non hanno voglia di condividere gli spazi con gli ospiti o con altri clienti. Una suite privata risolve questo: dentro ci siete solo voi, con i vostri tempi, la vostra musica e la vostra conversazione." },
      { title: "Cucina e living per prosecco, trucchi e foto", body: "Infinity offre 77 m² con living e cucina completa, adatti se siete in due o tre persone e desiderate spazio per sistemarvi, bere qualcosa o scattare fotografie. Passion, più raccolta da 55 m², è indicata se la preferita è un’atmosfera più intima. Non sono inclusi allestimenti, bevande extra o servizi professionali: ogni dettaglio va concordato prima.", bullets: ["Data e orario desiderato per l’ingresso.", "Numero esatto di persone presenti.", "Eventuali necessità da preparare prima dell’arrivo."] },
      { title: "Niente pubblico, niente turni, niente orari della spa comune", body: "Jacuzzi e sauna sono interne alla suite e restano a uso esclusivo per tutta la durata concordata. Non ci sono tempi massimi di permanenza nella vasca, non c’è nessuno che aspetta il vostro turno. L’ingresso avviene con tastierino, senza passare da reception." },
    ], faqs: [{ q: "Possiamo entrare in 3 o 4 persone?", a: "Sì, ma ogni composizione va concordata prima della prenotazione per definire condizioni, tariffa e compatibilità con gli spazi." }, { q: "Possiamo far entrare parrucchiere, make-up artist o fotografo?", a: "La presenza di professionisti esterni va comunicata e autorizzata prima: non è automatica con la prenotazione." }, { q: "C’è una formula solo per qualche ora?", a: "Potete chiedere disponibilità per utilizzi brevi. Non sono pubblicate tariffe a ore; le condizioni si definiscono direttamente." }],
  },
  {
    slug: "spa-privata-persona-sola-sicilia", label: "Solo per te", line: "Nessuno.\nNemmeno il telefono.", detail: "Una persona, una suite, quattro mura. Il resto del mondo fuori.",
    primaryKeyword: "spa privata persona sola Sicilia", title: "Spa privata per una persona sola vicino ad Agrigento", metaTitle: "Spa privata persona sola: reset a Porto Empedocle | Euphoria", metaDescription: "Stacca per davvero a Porto Empedocle: suite con jacuzzi e sauna private per una persona sola. Ingresso autonomo, cucina completa, zero persone intorno. Nessun obbligo di essere in due.",
    ogTitle: "Nessuno. Nemmeno il telefono.", ogDescription: "Euphoria per una persona sola: privacy, relax e zero obblighi a Porto Empedocle.", suggestedSuite: "passion", relatedBlogSlugs: ["perche-andare-in-spa-da-solo-persona-sola", "dopo-esami-lavoro-stacca-in-spa-privata"],
    hero: { eyebrow: "Reset in solitaria", h1: "Nessuno. Nemmeno il telefono.", sub: "Chi l’ha detto che bisogna essere in due per andare in spa? Se hai bisogno di staccare da esami, lavoro o semplicemente da un periodo pesante, Euphoria è una suite privata a Porto Empedocle, in provincia di Agrigento. Ingresso autonomo, jacuzzi e sauna interne, nessuno intorno." , image: passion },
    blocks: [
      { title: "Non è “andare da soli”: è scegliere di non vedere nessuno", body: "A volte la differenza la fa poter stare in silenzio, senza dover rispondere, senza dover fare bella figura. Entrambe le suite sono chiuse e ad uso esclusivo: entri, metti il telefono in silenzioso e il mondo resta fuori per qualche ora o per l’intera notte." },
      { title: "Tutto dentro, per non dover uscire", body: "Cucina completa, Wi-Fi, condizionatori e ingresso autonomo con tastierino sono inclusi. Se vuoi portarti da bere, qualcosa da mangiare o guardare una serie, puoi farlo senza chiedere permessi. Il pernottamento include l’aperitivo di benvenuto.", bullets: ["Scegli data e formula: day use o pernottamento.", "Preferisci Passion (55 m²) o Infinity (77 m²).", "Comunica eventuali orari particolari di arrivo."] },
      { title: "Passion più veloce da “sentire tua”, Infinity più spazio", body: "Per una persona sola, Passion da 55 m² è la soluzione più immediata: ambienti uniti, tutto a portata di mano, sensazione di un piccolo bozzolo. Infinity da 77 m² va bene se invece preferisci camminare, avere una zona living separata o goderti più aria. Jacuzzi e sauna sono presenti in entrambe." },
    ], faqs: [{ q: "È prevista una tariffa scontata per una persona sola?", a: "Le tariffe sono basate sulla suite e non sul numero di persone. Se vuoi richiedere una formula personalizzata, scrivici direttamente." }, { q: "Posso ordinare generi alimentari o bevande da fuori?", a: "Sì, la cucina è disponibile. Sono esclusi dal prezzo però generi extra e servizi aggiuntivi oltre all’aperitivo incluso nel pernottamento." }, { q: "Qualcuno mi vede entrare o uscire?", a: "L’accesso è autonomo con codice, senza passare da reception. Non incontrerete personale se non concordato." }],
  },
  {
    slug: "spa-privata-due-amiche-porto-empedocle", label: "Tu & La Tua Amica", line: "Voi due.\nTutto il resto no.", detail: "Jacuzzi, sauna, un bicchiere e nessuno che disturba.",
    primaryKeyword: "spa privata due amiche Porto Empedocle", title: "Spa privata con la migliore amica vicino ad Agrigento", metaTitle: "Spa privata due amiche Porto Empedocle | Euphoria", metaDescription: "Un momento privato tra due amiche a Porto Empedocle: jacuzzi e sauna in suite, cucina completa, ingresso autonomo. Nessun pubblico, nessun pacchetto forzato.", ogTitle: "Voi due. Tutto il resto no.", ogDescription: "Spa privata tra amiche a Porto Empedocle, in provincia di Agrigento.", suggestedSuite: "infinity", relatedBlogSlugs: ["perche-andare-in-spa-da-solo-persona-sola"],
    hero: { eyebrow: "Relax tra amiche", h1: "Voi due. Tutto il resto no.", sub: "Se tu e la tua migliore amica cercate un posto in provincia di Agrigento dove chiacchierare, rilassarvi e prendervi un momento senza nessun altro intorno, Euphoria è una suite privata a Porto Empedocle con jacuzzi e sauna interne, ingresso autonomo e cucina completa.", image: infinity },
    blocks: [
      { title: "Niente pacchetti “girls day”: solo una porta da chiudere", body: "Non serve un nome commerciale per stare tra amiche. Serve uno spazio privato dove non incrociate altre persone, non avete turni per la jacuzzi e non dovete adattarvi agli orari di una spa condivisa. Dentro Euphoria la porta si chiude e ci siete solo voi." },
      { title: "Aperitivo fai-da-te o semplice pausa: scegliete voi", body: "La suite ha cucina completa e potete portare quello che preferite: prosecco, bibite, stuzzichini o qualunque cosa vi va bene. Nel caso del pernottamento è incluso un aperitivo di benvenuto standard con tagliere e prosecco. Ogni altro extra non è automatico e va concordato.", bullets: ["Data e orario di arrivo preferiti.", "Formula che preferite: diurna o pernottamento.", "Numero di persone (se più di due, va concordato prima)."] },
      { title: "Infinity 77 m² per più respiro, Passion 55 m² per stare vicino", body: "Se siete in due e volete più spazio per stare comode, scattare foto o muovervi tra living e cucina, Infinity con i suoi 77 m² è la scelta più adatta. Passion, da 55 m², è invece più raccolta e intima. Entrambe hanno jacuzzi e sauna private." },
    ], faqs: [{ q: "Possiamo venire in 3 o 4 amiche?", a: "Solo dopo accordo diretto. Componete la richiesta esatta su WhatsApp e la valutiamo insieme, confermando condizioni e tariffa." }, { q: "Si può usare la cucina per preparare qualcosa?", a: "Sì, la cucina è completa. Non sono inclusi però generi alimentari o bevande extra, salvo l’aperitivo del pernottamento." }, { q: "Ci sono orari fissi per la vasca o la sauna?", a: "No. Jacuzzi e sauna sono interne e senza limiti di turno per tutta la durata della prenotazione." }],
  },
  {
    slug: "compleanno-spa-privata-senza-festa", label: "Compleanno", line: "Il tuo giorno.\nSenza confusione.", detail: "Con una o due persone care. Zero tavolate, zero obblighi.",
    primaryKeyword: "compleanno spa privata senza festa Porto Empedocle", title: "Compleanno senza festa in spa privata vicino ad Agrigento", metaTitle: "Compleanno spa privata senza casino | Euphoria", metaDescription: "Un compleanno diverso a Porto Empedocle: niente tavolata, niente casino. Suite con jacuzzi e sauna private, poche persone care, zero obblighi di festa. Ideato per chi odia la confusione.", ogTitle: "Il tuo giorno. Senza confusione.", ogDescription: "Compleanno in privato: Euphoria a Porto Empedocle, vicino ad Agrigento.", suggestedSuite: "infinity", relatedBlogSlugs: ["compleanno-diverso-senza-festa-spa-privata"],
    hero: { eyebrow: "Niente tavolate, niente casino", h1: "Il tuo giorno. Senza confusione.", sub: "Se il tuo compleanno perfetto non ha venti invitati, musica alta e cento messaggi vocali, Euphoria è una suite privata a Porto Empedocle in provincia di Agrigento. Porta con te una o due persone care: jacuzzi e sauna sono interne, l’ingresso è autonomo, la cucina è completa.", image: infinity },
    blocks: [
      { title: "Il regalo non è un oggetto: è poter stare senza fretta", body: "Per chi non ama stare al centro dell’attenzione, un compleanno in privato è spesso la scelta migliore. Non ci sono brindisi programmati, nessun obbligo di discorsetto, nessuna torta da tagliare se non volete. Potete semplicemente stare, usare la jacuzzi o la sauna, bere qualcosa e godervi la serata come preferite." },
      { title: "Torta, dediche o sorprese: tutto da concordare prima", body: "Se vuoi una torta, fiori, petali o una piccola dedica, chiedi in anticipo quali opzioni sono possibili. Questi elementi non sono inclusi automaticamente né garantiti; prezzi e disponibilità si definiscono direttamente con la struttura. L’aperitivo di benvenuto, invece, è incluso nel pernottamento.", bullets: ["Data e orario di arrivo previsti.", "Numero esatto di persone che partecipano.", "Qualsiasi dettaglio sorpresa da verificare in anticipo."] },
      { title: "Più spazio in Infinity, più intimità in Passion", body: "Infinity, con 77 m² tra zona notte, living e cucina, è la scelta più comoda per un gruppo piccolo di 2 o 3 persone. Passion, da 55 m², è più raccolta e adatta a due persone che preferiscono vicinanza e una sola atmosfera. Jacuzzi e sauna sono presenti in entrambe." },
    ], faqs: [{ q: "Possiamo portare la torta o altre cose da fuori?", a: "Sì, ma per sicurezza segnalalo prima. Non sono inclusi extra oltre all’aperitivo del pernottamento." }, { q: "Possiamo fare una piccola sorpresa con allestimento?", a: "Va richiesta e confermata prima: non tutti gli allestimenti sono possibili e possono avere un costo aggiuntivo." }, { q: "Possiamo stare in 3 o 4 persone?", a: "La composizione va verificata prima della prenotazione; non è consentito superare i numeri concordati." }],
  },
  {
    slug: "stacca-spa-privata-dopo-esami-lavoro", label: "Dopo il periodo pesante", line: "Hai finito.\nOra fermati.", detail: "Fine esami, consegna, progetto chiuso. Reset a porta chiusa.",
    primaryKeyword: "dopo esami lavoro spa privata Agrigento", title: "Dopo esami, tesi o lavoro: spa privata vicino ad Agrigento", metaTitle: "Dopo esami lavoro: reset in spa privata | Euphoria", metaDescription: "Dopo esami, consegna tesi, progetto chiuso o cambio lavoro: suite privata a Porto Empedocle con jacuzzi e sauna interne, telefono silenzioso e zero obblighi. Una notte o un utilizzo diurno per staccare davvero.", ogTitle: "Hai finito. Ora fermati.", ogDescription: "Reset in spa privata dopo un periodo pesante: Euphoria a Porto Empedocle.", suggestedSuite: "passion", relatedBlogSlugs: ["dopo-esami-lavoro-stacca-in-spa-privata", "perche-andare-in-spa-da-solo-persona-sola"],
    hero: { eyebrow: "Il reset che ti meriti", h1: "Hai finito. Ora fermati.", sub: "Se hai appena chiuso un periodo pesante tra esami, tesi, progetti o lavoro, Euphoria è una suite privata a Porto Empedocle, in provincia di Agrigento. Ingresso autonomo, jacuzzi e sauna interne, cucina completa: entra, chiudi la porta e non fai niente per qualche ora.", image: passion },
    blocks: [
      { title: "Non hai bisogno di “festeggiare”: hai bisogno di spegnere", body: "Dopo settimane in cui la testa è stata sempre accesa, spesso la festa con gli amici non è la cosa giusta. Quello che serve è pace: un ambiente dove non vedere nessuno, non rispondere al telefono, non prendere decisioni. Le due suite sono chiuse, isolate e ad uso esclusivo per tutta la durata concordata." },
      { title: "Nessun itinerario dentro la suite: l’ideale è fare zero", body: "Jacuzzi, sauna, serie TV, pisolino nel pomeriggio o una bevanda in cucina: non c’è una lista di cose da fare nella suite. L’ingresso con tastierino vi lascia autonomi sull’orario; la cucina completa vi permette di portare quello che preferite. Nel caso di pernottamento è incluso anche l’aperitivo di benvenuto.", bullets: ["Data e formula (giorno o notte).", "Passion (55 m²) o Infinity (77 m²).", "Orario di arrivo, se particolare."] },
      { title: "Solo tu, o con una persona senza parole", body: "Se vuoi veramente staccare, meglio venire da soli. Se invece preferisci una persona con cui stare anche in silenzio, puoi: ogni formula e ogni numero vanno però concordati prima, per evitare sorprese. Non sono ammesse persone aggiuntive non dichiarate." },
    ], faqs: [{ q: "Meglio la formula diurna o il pernottamento?", a: "Dipende da quanto ti senti svuotato. 3 o 4 ore possono bastare; un pernottamento invece ti lascia il tempo di non avere fretta." }, { q: "Posso spegnere il telefono e non disturbarmi per nessun motivo?", a: "Sì, è l’ambiente ideale per questo. Non ci sono chiamate o interruzioni non richieste." }, { q: "Si possono chiedere orari più flessibili il giorno dopo?", a: "Late check-out o uscite posticipate non sono inclusi. Chiedi disponibilità e condizioni prima di prenotare." }],
  },
  {
    slug: "regalo-voucher-spa-privata-sicilia", label: "Voucher Regalo", line: "Un momento.\nPiù di un oggetto.", detail: "Euphoria come regalo: mamma, amica, laurea, testimone. Formule da concordare.",
    primaryKeyword: "voucher regalo spa privata Sicilia esperienza", title: "Voucher regalo spa privata in Sicilia vicino ad Agrigento", metaTitle: "Voucher regalo spa privata: esperienza Euphoria | Euphoria", metaDescription: "Un’idea regalo diversa da fare a mamma, migliore amica, laurea, testimone o compleanno: una notte o un’esperienza in suite privata Euphoria a Porto Empedocle. Formula e importo si definiscono direttamente su WhatsApp, senza promesse automatiche di voucher a data aperta.", ogTitle: "Un momento. Più di un oggetto.", ogDescription: "Euphoria come regalo: voucher da concordare direttamente a Porto Empedocle.", suggestedSuite: undefined as "passion" | "infinity" | undefined, relatedBlogSlugs: ["regalo-esperienza-spa-privata-piu-forte-di-oggetti"],
    hero: { eyebrow: "L’esperienza che non si butta", h1: "Un momento. Più di un oggetto.", sub: "Se cerchi un regalo che non finisca in un cassetto, Euphoria è una suite privata a Porto Empedocle in provincia di Agrigento, con jacuzzi e sauna interne. Importo, formula e qualsiasi dettaglio del voucher si definiscono direttamente su WhatsApp: non vengono rilasciati voucher generici a data aperta senza una conferma precisa.", image: passion },
    blocks: [
      { title: "Per chi è perfetto: praticamente chiunque meriti un “stacco”", body: "Mamma, migliore amica, sorella, testimone di matrimonio, persona che si è laureata, collega promossa, semplicemente qualcuno che sta attraversando un periodo pesante: l’idea di regalare alcune ore o una notte in privato funziona in moltissimi casi. Non devi scegliere taglie, colori o profumi.", },
      { title: "Come funziona: tutto via WhatsApp, niente formule preconfezionate", body: "Non offriamo un listino fisso di voucher preconfezionati. Scriveteci direttamente, spiegate occasione, importo che avete in mente o formula preferita (per esempio una notte, oppure un utilizzo diurno) e vi confermiamo se è possibile, a quali condizioni e per quale data. Solo dopo l’accordo completo la struttura prepara il documento personalizzato.", bullets: ["Occasione e persona a cui è rivolto il regalo.", "Importo o formula desiderata.", "Preferenze su come consegnarlo e tempi."] },
      { title: "Noi prepariamo il documento, chi lo riceve sceglie quando usarlo (entro limiti chiari)", body: "Dopo l’accordo su importo e formula è possibile preparare un documento personalizzato con dedica. Le date di validità e le condizioni di utilizzo vengono scritte in modo chiaro nel documento stesso e non sono estese senza accordo. Il destinatario sceglie Passion o Infinity e la data disponibile, contattandoci direttamente." },
    ], faqs: [{ q: "Posso creare un voucher per una cifra a mia scelta?", a: "Dipende dall’importo e dalla formula: scrivici la tua idea e valutiamo insieme, senza obbligo di conferma." }, { q: "Il voucher è spendibile quando si vuole, senza scadenza?", a: "No: ogni documento ha una scadenza chiara. Non vengono rilasciati voucher “a vita” o senza condizioni precise." }, { q: "Posso cambiare idea dopo l’acquisto?", a: "Le politiche di rimborso o modifica vengono definite caso per caso prima di confermare e riportate nell’accordo iniziale." }],
  },
] satisfies Occasion[]).map((occasion) => ({ ...occasion, dateModifiedISO: "2026-09-15" }));
